# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
