# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20171006_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
