# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_favorited'),
        ('authentification', '0003_auto_20171006_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='shop.Shop'),
        ),
    ]
