# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='favorited',
            field=models.ManyToManyField(related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
